packages:
  - name: launcher
    functions:
      - name: etf-trend-monitor
        runtime: python:default
        limits:
          timeout: 60000
          memory: 512
        web: false
        environment:
          TZ: "${TZ}"
          GHCR_USERNAME: "${GHCR_USERNAME}"
          GHCR_TOKEN: "${GHCR_TOKEN}"
          DO_TOKEN: "${DO_TOKEN}"
          DO_API: "https://api.digitalocean.com/v2"
          DO_REGION: "${DO_REGION}"
          DO_SIZE: "${DO_SIZE}"
          DO_IMAGE: "${DO_IMAGE}"
          DO_TAG: "ephemeral-daily-run"
          DO_APP_TAG: "app-runners"
          DO_SSH_KEY_ID: "${DO_SSH_KEY_ID}"
          JOB_IMAGE: "ghcr.io/mosesmc52/etf-trend-monitor:latest"
          TO_ADDRESSES: "${TO_ADDRESSES}"
          FROM_ADDRESS: "${FROM_ADDRESS}"
          AWS_SES_REGION_NAME: "${AWS_SES_REGION_NAME}"
          AWS_SES_ACCESS_KEY_ID: "${AWS_SES_ACCESS_KEY_ID}"
          AWS_SES_SECRET_ACCESS_KEY: "${AWS_SES_SECRET_ACCESS_KEY}"
        triggers:
          - name: sunday-9am-utc
            sourceType: scheduler
            sourceDetails:
              cron: "0 14 * * 0"
